name: GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{secrets.GCP_PROJECT_ID}}/node:18-alpine
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{secrets.GCP_CREDENTIALS}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t $IMAGE_NAME .


      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy nteste --image $IMAGE_NAME --region us-east5 --ingress=all --memory=128Mi --min-instances=1 --max-instances=8 --platform=managed --allow-unauthenticated


      